"""Add resume fields to candidate

Revision ID: ae6ca3089ad1
Revises: d0118701e826
Create Date: 2026-07-28 20:25:06.109301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae6ca3089ad1'
down_revision: Union[str, Sequence[str], None] = 'd0118701e826'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('resume_filename', sa.String(length=255), nullable=True))
    op.add_column('candidates', sa.Column('resume_path', sa.String(length=500), nullable=True))
    op.add_column('candidates', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('candidates', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'updated_at')
    op.drop_column('candidates', 'created_at')
    op.drop_column('candidates', 'resume_path')
    op.drop_column('candidates', 'resume_filename')
    # ### end Alembic commands ###
